name: pixify
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  firebase_analytics: ^11.4.4
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  firebase_database: ^11.3.4
  firebase_messaging: ^15.2.4
  flutter:
    sdk: flutter
    
  flutter_local_notifications: ^18.0.1
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  http: ^1.3.0
  image_cropper: ^9.0.0
  image_picker: ^1.1.2
  photo_manager: ^3.6.4
  provider: ^6.1.2
  shared_preferences: ^2.5.2
  supabase_flutter: ^2.8.4
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    -  assets/

  fonts:
    - family: Handwriting
      fonts:
        - asset: fonts/JustAnotherHand-Regular.ttf
